name: first workflow

env:
  WORKFLOW_VAR: "This is a workflow lvl var"
  
on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! this is the first job
      - name: checkout
        uses: actions/checkout@v6
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"
  secondjob:
    env:
      JOB_VAR: "This is a job var"
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo This is second job
          echo And this is a multi-line script
      - name: environment variables
        env:
          STEP_VAR: "This is a step var"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course this won't be displayed in the job"
          echo "The following are default (predefined) environment variables"          
          echo $GITHUB_ACTOR
          echo $GITHUB_JOB
          echo $GITHUB_REF

  
      

  
